spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: teste
    password: teste
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  liquibase:
    drop-first: false

server:
  error:
    include-message: always
    include-stacktrace: never

spring.jpa.show-sql: false