SET REFERENTIAL_INTEGRITY FALSE;
UPDATE PLAYER SET CURRENT_GAME_ID = null;
UPDATE PLAYER SET SCORE = 9999 WHERE ID = 1;
UPDATE PLAYER SET SCORE = 1991 WHERE ID = 2;
TRUNCATE TABLE GAME;
TRUNCATE TABLE ROUND;
SET REFERENTIAL_INTEGRITY TRUE;